dubbo:
  application:
    name: moon-dubbo-provider2 # 服务名
    id: moon-dubbo-provider2
  registry:
    address: zookeeper://192.168.1.102:12181 # 注册中心地址
  protocol:
    name: dubbo # 指定通信协议
    port: 20880 # 通信端口  这里指的是与消费者间的通信协议与端口
  provider:
    timeout: 10000 # 配置全局调用服务超时时间，dubbo默认是1s，肯定不够用呀
    retries: 3 # 重试3次
    delay: -1

service:
  version: 1.0.0

spring:
  kafka:
    bootstrap-servers: 192.168.1.102:19092  #bootstrap-servers：连接kafka的地址，多个地址用逗号分隔
    consumer:
      group-id: myGroup
      enable-auto-commit: true
      auto-commit-interval: 100ms
      properties:
        session.timeout.ms: 15000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest

elasticsearch:
  host: 192.168.1.102
  port: 19205
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
