dubbo:
  application:
    name: moon-dubbo-consumer # 服务名
    id: moon-dubbo-consumer
  registry:
    address: zookeeper://192.168.1.102:12181 # 注册中心地址
  protocol:
    name: dubbo # 指定通信协议
    port: 20880 # 通信端口  这里指的是与消费者间的通信协议与端口
server:
  port: 8081
service:
  version: 1.0.0